# Builds Rt as a Python extension module.
# Requires SWIG and Python distutils, and well, Python.

.PHONY: all install clean

all :
	swig -c++ -python Rt.i
	python setup.py build

install :
	sudo python setup.py install

clean :
	rm -rf build Rt_wrap.cxx Rt.py* 

